### ISSUE TITLE
Throw Exception on QueryBuilder::forge() without inherited class

### ISSUE THREAD

**Issue by pips-** [pragma-framework/core#12]
While doing unit tests for QueryBuilder class, I realize I can not call the `forge()` method on the bare object.

Trying something like this:

```php
$qb = QueryBuilder::forge();
```

Ends up in constructor being called without argument, giving a inconsistent QueryBuilder object missing a proper $table attribute value.

Changing this class to be abstract would not allow to build dummy object not linked to any table, as it is the main purpose of the QueryBuilder.

By the way, calling `forge()` with a class name as parameter may not completely solve this issue, the class name may be any existing class which may not be a valid children of QueryBuilder.

For this one, I suggest we use a `is_subclass_of()` on the string parameter if any. For the former, declare the class as abstract should be enough.

**Comment by pips-** [comment]
Seen with @cyrilrouyer, `QueryBuilder` should not be abstract, in order to keep a way query the database by passing table to the constructor, but `QueryBuilder::forge()` should throw an exception if used with no parameter or `static` does not resolve to a inherited class.

**Comment by pips-** [comment]
Continuing building unit tests, I came across another similar issue with `QuerBuilder::get_objects()`.

As this it also relies on `new static()` constructor, I can not make a test for this method in the bare context of `QueryBuilder` object. So, we may want to throw an exception there too.

**Comment by pips-** [comment]
The same may apply to `QueryBuilder::first()`.

**Comment by pips-** [comment]
Same goes for `QueryBuilder::get_arrays()` since it relies on making a `new static()` to build up relations. Build fails since 976f950 (https://travis-ci.org/pragma-framework/core/jobs/252453523).

Shouldn't `QueryBuilder::get_arrays()` keep a straightforward logic on returning just arrays of elements and `Model` overloads this method? Relations are defined in `Model::add_relation()` anyway.

**Comment by cyrilrouyer** [comment]
closed with 18ac75f
